spring:
  application:
    name: client
  data:
    redis:
      host: 127.0.0.1
      port: 6379
Access-Control-Allow-Credentials: true
zoho:
    client-id: 1000.S9CMBC2Y5AO0CASPPMP8ADWKCYP8HM
    client-secret: 101c7a1f5aa5e5295d5b850bd7cd168a68849e18ab
    redirect-uri: "http://localhost:4200/zoho/callback"
    auth-url: "https://accounts.zoho.com/oauth/v2/auth"
    token-url: "https://accounts.zoho.com/oauth/v2/token"
    scope: "ZohoBooks.settings.READ,ZohoBooks.contacts.ALL,ZohoBooks.invoices.CREATE,ZohoBooks.invoices.READ,ZohoBooks.invoices.UPDATE,ZohoBooks.invoices.DELETE,ZohoBooks.customerpayments.CREATE,ZohoBooks.expenses.CREATE,ZohoBooks.banking.READ"
    openai-api-key: ${OPENAI_API_KEY}
    currency-id: "USD"
    payment-mode-default: "Cash"
    mileageEmployeeId: ""

